# Site settings
title: Luiz Cavalcanti
description: 'Software developer & consultant'
url: 'http://cavalcanti.info'
baseurl: ''
profilepic: '/images/profile.jpg'
bkimage: '/images/background.jpg'
# google_analytics: UA-XXXXXX-X
font_awesome: '10ecd1cc72.js'

author:
  name: 'Luiz Cavalcanti'
  email: cavalcanti.luiz@gmail.com
  twitter_username: luizcavalcanti
#  facebook_username: blablabla
  github_username:  luizcavalcanti
  linkedin_username:  luizcavalcanti
  # meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

# plugins: ['jekyll-paginate']
# exclude: ['some_file']
