version: "3.1"

services:
  nginx:
    image: nginx:1-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - logs:/etc/nginx/logs
    depends_on:
      - site
      - blog

  site:
    image: nginx:1-alpine
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - logs:/etc/nginx/logs
      - ./www:/www

  blog:
    image: wordpress:4-php7.0
    restart: always
    environment:
      - WORDPRESS_DB_PASSWORD
    volumes:
      - ./blog/wp-content:/var/www/html/wp-content
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - database-files:/var/lib/mysql

volumes:
  logs:
  database-files:
